"""add_idempotency_key_to_order

Revision ID: 579b53d42293
Revises: 7015b831481a
Create Date: 2026-04-26 22:37:20.254130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '579b53d42293'
down_revision = '7015b831481a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_adminauditlog_admin_id', table_name='adminauditlog')
    op.drop_table('adminauditlog')
    op.drop_index('category_slug_key', table_name='category')
    op.add_column('order', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_order_idempotency_key'), 'order', ['idempotency_key'], unique=False)
    op.drop_column('order', 'deleted_at')
    op.drop_constraint('passwordreset_token_key', 'passwordreset', type_='unique')
    op.drop_index('ix_passwordreset_token', table_name='passwordreset')
    # Use index instead of unique constraint if it was already an index
    op.create_index(op.f('ix_passwordreset_token'), 'passwordreset', ['token'], unique=True)
    
    op.alter_column('product', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_product_list_active_cat_created', table_name='product')
    op.drop_index('ix_product_sales_count', table_name='product')
    op.drop_index('product_sku_key', table_name='product')
    
    op.alter_column('productvariant', 'sku',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=120),
               existing_nullable=True)
    
    op.drop_column('review', 'deleted_at')
    op.drop_constraint('tokenblacklist_token_key', 'tokenblacklist', type_='unique')
    op.drop_index('ix_tokenblacklist_token', table_name='tokenblacklist')
    op.create_index(op.f('ix_tokenblacklist_token'), 'tokenblacklist', ['token'], unique=True)
    
    op.drop_constraint('twofactorsecret_user_id_key', 'twofactorsecret', type_='unique')
    op.drop_index('ix_twofactorsecret_user_id', table_name='twofactorsecret')
    op.create_index(op.f('ix_twofactorsecret_user_id'), 'twofactorsecret', ['user_id'], unique=True)
    
    op.alter_column('user', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('uq_user_username', 'user', type_='unique')
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
# ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    
    op.alter_column('user', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    
    op.drop_index(op.f('ix_twofactorsecret_user_id'), table_name='twofactorsecret')
    op.create_index('ix_twofactorsecret_user_id', 'twofactorsecret', ['user_id'], unique=False)
    op.create_unique_constraint('twofactorsecret_user_id_key', 'twofactorsecret', ['user_id'])
    
    op.drop_index(op.f('ix_tokenblacklist_token'), table_name='tokenblacklist')
    op.create_index('ix_tokenblacklist_token', 'tokenblacklist', ['token'], unique=False)
    op.create_unique_constraint('tokenblacklist_token_key', 'tokenblacklist', ['token'])
    
    op.add_column('review', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    
    op.alter_column('productvariant', 'sku',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    
    op.create_index('product_sku_key', 'product', ['sku'], unique=True)
    op.create_index('ix_product_sales_count', 'product', ['sales_count'], unique=False)
    op.create_index('ix_product_list_active_cat_created', 'product', ['is_active', 'category', 'created_at'], unique=False)
    
    op.alter_column('product', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    
    op.drop_index(op.f('ix_passwordreset_token'), table_name='passwordreset')
    op.create_index('ix_passwordreset_token', 'passwordreset', ['token'], unique=False)
    op.create_unique_constraint('passwordreset_token_key', 'passwordreset', ['token'])
    
    op.add_column('order', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.drop_index(op.f('ix_order_idempotency_key'), table_name='order')
    op.drop_column('order', 'idempotency_key')
    op.create_index('category_slug_key', 'category', ['slug'], unique=True)
    
    op.create_table('adminauditlog',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('admin_id', sa.INTEGER(), nullable=False),
        sa.Column('action', sa.VARCHAR(), nullable=False),
        sa.Column('entity_type', sa.VARCHAR(), nullable=False),
        sa.Column('entity_id', sa.INTEGER(), nullable=True),
        sa.Column('changes', sa.VARCHAR(), nullable=True),
        sa.Column('ip_address', sa.VARCHAR(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name='adminauditlog_admin_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='adminauditlog_pkey')
    )
    op.create_index('ix_adminauditlog_admin_id', 'adminauditlog', ['admin_id'], unique=False)
# ### end Alembic commands ###
