"""order reviews and sunscription tables

Revision ID: 5aa7b199e4b3
Revises: cf3b83e2c22d
Create Date: 2026-04-11 10:23:29.114748

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5aa7b199e4b3'
down_revision = 'cf3b83e2c22d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('category', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('category', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.drop_index('ix_product_category_id', table_name='product')
    op.drop_index('ix_product_sku', table_name='product')
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.create_index('ix_product_sku', 'product', ['sku'], unique=False)
    op.create_index('ix_product_category_id', 'product', ['category_id'], unique=False)
    op.drop_column('category', 'sort_order')
    op.drop_column('category', 'is_active')
    op.drop_column('category', 'image_url')
    # ### end Alembic commands ###
