"""test update

Revision ID: a4011e455772
Revises: a83bbcaf54ed
Create Date: 2026-04-10 08:45:52.818452

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import inspect


revision = 'a4011e455772'
down_revision = 'a83bbcaf54ed'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)

    if not inspector.has_table("product"):
        op.create_table(
            "product",
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("price", sa.Float(), nullable=False),
            sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("in_stock", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    if not inspector.has_table("user"):
        op.create_table(
            "user",
            sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("is_admin", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
