export const V1 = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    login2fa: "/auth/login-2fa",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    profile: "/auth/profile",
    profilePut: "/auth/profile",
    verifyEmail: "/auth/verify-email",
    resendEmailVerification: "/auth/resend-email-verification",
    passwordResetRequest: "/auth/password-reset/request",
    passwordResetConfirm: "/auth/password-reset/confirm",
    passwordChange: "/auth/password/change",
    twoFaSetup: "/auth/2fa/setup",
    twoFaEnable: "/auth/2fa/enable",
    twoFaDisable: "/auth/2fa/disable",
    twoFaBackupCodes: "/auth/2fa/backup-codes",
    accountDelete: "/auth/account/delete",
  },
  products: {
    list: "/products/",
    categories: "/products/categories",
    category: (id: number) => `/products/categories/${id}`,
    detail: (id: number) => `/products/${id}`,
    bySlug: (slug: string) => `/products/slug/${encodeURIComponent(slug)}`,
    search: "/products/search",
  },
  cart: {
    list: "/cart/",
    withWishlist: "/cart/with-wishlist",
    addItem: "/cart/items",
    updateItem: (itemId: number) => `/cart/items/${itemId}`,
    deleteItem: (itemId: number) => `/cart/items/${itemId}`,
    clear: "/cart/",
  },
  orders: {
    list: "/orders/",
    create: "/orders/",
    detail: (id: number) => `/orders/${id}`,
    invoicePdf: (id: number) => `/orders/${id}/invoice/pdf`,
  },
  reviews: {
    create: "/reviews",
    product: (productId: number) => `/reviews/product/${productId}`,
    canReview: (productId: number) => `/reviews/product/${productId}/can-review`,
    mine: "/reviews/user/me",
    delete: (reviewId: number) => `/reviews/${reviewId}`,
  },
  wishlist: {
    list: "/wishlist/",
    add: "/wishlist/items",
    remove: (itemId: number) => `/wishlist/items/${itemId}`,
  },
  payments: {
    paystackInitialize: "/payments/paystack/initialize",
    paystackVerify: (reference: string) =>
      `/payments/paystack/verify/${encodeURIComponent(reference)}`,
    paystackWebhook: "/payments/paystack/webhook",
  },
  subscriptions: {
    subscribe: "/subscriptions/subscribe",
    unsubscribe: "/subscriptions/unsubscribe",
    verify: (token: string) => `/subscriptions/verify/${encodeURIComponent(token)}`,
  },
  admin: {
    analyticsDashboard: "/admin/analytics/dashboard",
    analyticsRevenue: "/admin/analytics/revenue",
    users: "/admin/users",
    products: "/admin/products",
    product: (id: number) => `/admin/products/${id}`,
    categories: "/admin/categories",
    category: (id: number) => `/admin/categories/${id}`,
    orders: "/admin/orders",
    order: (id: number) => `/admin/orders/${id}`,
    orderInvoicePdf: (id: number) => `/admin/orders/${id}/invoice/pdf`,
    orderStatus: (id: number) => `/admin/orders/${id}/status`,
    orderTracking: (id: number) => `/admin/orders/${id}/tracking`,
    paymentsTransactions: "/admin/payments/transactions",
    reviews: "/admin/reviews",
    review: (id: number) => `/admin/reviews/${id}`,
    userDeactivate: (id: number) => `/admin/users/${id}/deactivate`,
    userActivate: (id: number) => `/admin/users/${id}/activate`,
    userPromoteAdmin: (id: number) => `/admin/users/${id}/promote-admin`,
    userRevokeAdmin: (id: number) => `/admin/users/${id}/revoke-admin`,
  },
} as const;
