export const V1 = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    login2fa: "/auth/login-2fa",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    profile: "/auth/profile",
    profilePut: "/auth/profile",
    verifyEmail: "/auth/verify-email",
    resendEmailVerification: "/auth/resend-email-verification",
    passwordResetRequest: "/auth/password-reset/request",
    passwordResetConfirm: "/auth/password-reset/confirm",
    passwordChange: "/auth/password/change",
    twoFaSetup: "/auth/2fa/setup",
    twoFaEnable: "/auth/2fa/enable",
    twoFaDisable: "/auth/2fa/disable",
    twoFaBackupCodes: "/auth/2fa/backup-codes",
    accountDelete: "/auth/account/delete",
    googleStart: "/auth/google/start",
    googleCallback: "/auth/google/callback",
    googleVerify2fa: "/auth/google/verify-2fa",
  },
  products: {
    list: "/products/",
    categories: "/products/categories",
    category: (id: number) => `/products/categories/${id}`,
    detail: (id: number) => `/products/${id}`,
    bySlug: (slug: string) => `/products/slug/${encodeURIComponent(slug)}`,
    search: "/products/search",
  },
  cart: {
    list: "/cart/",
    withWishlist: "/cart/with-wishlist",
    addItem: "/cart/items",
    updateItem: (itemId: number) => `/cart/items/${itemId}`,
    deleteItem: (itemId: number) => `/cart/items/${itemId}`,
    clear: "/cart/",
  },
  orders: {
    list: "/orders/",
    create: "/orders/",
    shippingOptions: "/orders/shipping-options",
    detail: (id: number) => `/orders/${id}`,
    invoicePdf: (id: number) => `/orders/${id}/invoice/pdf`,
  },
  reviews: {
    create: "/reviews",
    product: (productId: number) => `/reviews/product/${productId}`,
    canReview: (productId: number) => `/reviews/product/${productId}/can-review`,
    mine: "/reviews/user/me",
    delete: (reviewId: number) => `/reviews/${reviewId}`,
    media: (reviewId: number) => `/reviews/${reviewId}/media`,
    mediaItem: (reviewId: number, mediaId: number) =>
      `/reviews/${reviewId}/media/${mediaId}`,
  },
  returns: {
    createForOrder: (orderId: number) => `/orders/${orderId}/returns`,
    listForOrder: (orderId: number) => `/orders/${orderId}/returns`,
    myList: "/returns/",
    detail: (returnId: number) => `/returns/${returnId}`,
    cancel: (returnId: number) => `/returns/${returnId}`,
  },
  productVariants: {
    listForProduct: (productId: number) => `/products/${productId}/variants`,
  },
  productImages: {
    listForProduct: (productId: number) => `/products/${productId}/images`,
  },
  wishlist: {
    list: "/wishlist/",
    add: "/wishlist/items",
    remove: (itemId: number) => `/wishlist/items/${itemId}`,
  },
  payments: {
    paystackInitialize: "/payments/paystack/initialize",
    paystackVerify: (reference: string) =>
      `/payments/paystack/verify/${encodeURIComponent(reference)}`,
    paystackWebhook: "/payments/paystack/webhook",
  },
  subscriptions: {
    subscribe: "/subscriptions/subscribe",
    unsubscribe: "/subscriptions/unsubscribe",
    verify: (token: string) => `/subscriptions/verify/${encodeURIComponent(token)}`,
  },
  admin: {
    analyticsDashboard: "/admin/analytics/dashboard",
    analyticsRevenue: "/admin/analytics/revenue",
    users: "/admin/users",
    usersPermissionCatalog: "/admin/users/permission-catalog",
    usersStaffAccounts: "/admin/users/staff-accounts",
    products: "/admin/products",
    product: (id: number) => `/admin/products/${id}`,
    categories: "/admin/categories",
    category: (id: number) => `/admin/categories/${id}`,
    categoryImage: (id: number) => `/admin/categories/${id}/image`,
    orders: "/admin/orders",
    order: (id: number) => `/admin/orders/${id}`,
    orderInvoicePdf: (id: number) => `/admin/orders/${id}/invoice/pdf`,
    orderStatus: (id: number) => `/admin/orders/${id}/status`,
    orderTracking: (id: number) => `/admin/orders/${id}/tracking`,
    paymentsTransactions: "/admin/payments/transactions",
    inventoryLogs: "/admin/inventory/logs",
    inventoryStockLevels: "/admin/inventory/stock-levels",
    inventoryAdjustments: "/admin/inventory/adjustments",
    coupons: "/admin/coupons",
    coupon: (id: number) => `/admin/coupons/${id}`,
    settings: "/admin/settings",
    reviews: "/admin/reviews",
    review: (id: number) => `/admin/reviews/${id}`,
    userDeactivate: (id: number) => `/admin/users/${id}/deactivate`,
    userActivate: (id: number) => `/admin/users/${id}/activate`,
    userPromoteAdmin: (id: number) => `/admin/users/${id}/promote-admin`,
    userRevokeAdmin: (id: number) => `/admin/users/${id}/revoke-admin`,
    userStaffRole: (id: number) => `/admin/users/${id}/staff-role`,
    returns: "/admin/returns",
    return: (id: number) => `/admin/returns/${id}`,
    returnStatus: (id: number) => `/admin/returns/${id}/status`,
    searchSummary: "/admin/search-analytics/summary",
    searchTop: "/admin/search-analytics/top",
    searchZero: "/admin/search-analytics/zero-results",
    variants: "/admin/variants",
    variant: (id: number) => `/admin/variants/${id}`,
    productsBulkImport: "/admin/products/bulk-import",
    productsLowStock: "/admin/products/low-stock/list",
    productsLowStockAlerts: "/admin/products/low-stock/alerts",
  },
} as const;
